name: nf
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - ncurses
 - openjdk
 - xz
 - lz4-c
 - lbzip2
 - pigz
 - zstd<=1.3.3
 # remove for now -- not using and conflicts with diamond
 #- dsrc=2015.06.04
 - amos=3.1.0
 - awscli>=1.15.16
 - bbmap=38.22
 - bedtools=2.27.1
 - blast=2.7.1
 - bwa=0.7.17
 - centrifuge=1.0.4
 - cutadapt=1.18
 - diamond=0.9.24
 - flash=1.2.11
# these two are needed for fastqc to work
 - fontconfig
 - font-ttf-inconsolata
 - fastqc=0.11.8
 - khmer=2.1.2
 - krakenuniq=0.5.7
 - krona=2.7
 - mafft
 - mira=4.9.6
 - nextflow=18.10.1
 - pear=0.9.6
 - perl>=5.12.0
 - perl-biox-seq
 - perl-bioperl
 - samtools=1.9
 - trim-galore=0.5.0
 - perl-app-cpanminus
 - perl-file-sharedir-install
 - perl-dbi
 - perl-dbd-sqlite
 - entrez-direct
