name: nf
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - ncurses
 - openjdk
 - dsrc=2015.06.04
 - awscli>=1.15.16
 - bedtools=2.27.1
 - blast=2.7.1
 - bwa=0.7.17
 - centrifuge=1.0.3
 - cutadapt=1.16
 - fastqc=0.11.7
 - khmer=2.1.2
 - krona=2.7
 - mira=4.9.6
 - nextflow=0.29.0
 - pear=0.9.6
 - perl>=5.12.0
 - perl-biox-seq
 - samtools=1.8
 - trim-galore=0.4.5
